---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgbackrest-controller
  name: pgbackrest-controller
  namespace: cnpg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbackrest-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgbackrest-controller
    spec:
      containers:
        - args:
            - operator
            - --server-cert=/server/tls.crt
            - --server-key=/server/tls.key
            - --client-cert=/client/tls.crt
            - --server-address=:9090
            - --log-level=debug  # not yet implemented
          name: pgbackrest-controller
          ports:
            - containerPort: 9090
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 9090
          resources: {}
          volumeMounts:
            - mountPath: /server
              name: server
            - mountPath: /client
              name: client
      serviceAccountName: pgbackrest-controller
      volumes:
        - name: server
          secret:
            secretName: pgbackrest-controller-server-tls
        - name: client
          secret:
            secretName: pgbackrest-controller-client-tls
